# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

before_script:
  - apt update
  - apt install zip -y

deploy:
  stage: deploy
  script:
    - zip -r release.zip .
    - git add .
    - git commit -m "releasing.."
    - git push origin master
